spring:
  application:
    name: payments-challenge

  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/payments_challenge
    jdbc-url: jdbc:postgresql://0.0.0.0:5432/payments_challenge
    driver-class-name: org.postgresql.Driver
    username: 'payments_challenge'
    password: 'payments_challenge'
    platform: postgresql

  jpa:
    hibernate:
      ddl-auto: update